"""
Mappings de types CORRIGÉS pour toutes les APIs Hub'Eau
Généré AUTOMATIQUEMENT depuis les VRAIS endpoints CSV
Date de génération : 2025-10-28 15:05:05
Dernière modification: 2025-10-30 (piezometry_chroniques: migration /chroniques_tr → /chroniques)
Nombre de tables : 22

[INFO] Ce fichier a été VALIDÉ contre les endpoints CSV réels
       Seules les colonnes RÉELLEMENT retournées sont incluses

Sources: Endpoints CSV Hub'Eau (pas Swagger/OpenAPI)

IMPORTANT: piezometry_chroniques utilise /chroniques.csv (données historiques validées)
          et NON /chroniques_tr.csv (données télétransmises temps-réel)
"""

from typing import Dict, List, Tuple, Optional


# ============================================================================
# SCHÉMAS DES TABLES (générés depuis CSV réels)
# ============================================================================

HUBEAU_FIELD_TYPES: Dict[str, Dict[str, str]] = {
    "ecoulement_campagnes": {
        "code_campagne": "TEXT",
        "code_departement": "TEXT",
        "code_reseau": "TEXT",
        "code_type_campagne": "TEXT",
        "date_campagne": "TIMESTAMP",
        "libelle_departement": "TEXT",
        "libelle_reseau": "TEXT",
        "libelle_type_campagne": "TEXT",
        "nombre_modalite_ecoulement": "BIGINT",
        "uri_reseau": "TEXT",
    },

    "ecoulement_observations": {
        "code_bassin": "TEXT",
        "code_campagne": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_ecoulement": "TEXT",
        "code_projection_station": "TEXT",
        "code_region": "TEXT",
        "code_reseau": "TEXT",
        "code_station": "TEXT",
        "coordonnee_x_station": "DOUBLE PRECISION",
        "coordonnee_y_station": "DOUBLE PRECISION",
        "date_observation": "TIMESTAMP",
        "latitude": "DOUBLE PRECISION",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_ecoulement": "TEXT",
        "libelle_projection_station": "TEXT",
        "libelle_region": "TEXT",
        "libelle_reseau": "TEXT",
        "libelle_station": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "uri_cours_eau": "TEXT",
        "uri_reseau": "TEXT",
        "uri_station": "TEXT",
    },

    "ecoulement_stations": {
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_epsg_station": "TEXT",
        "code_projection_station": "TEXT",
        "code_region": "TEXT",
        "code_station": "TEXT",
        "coordonnee_x_station": "DOUBLE PRECISION",
        "coordonnee_y_station": "DOUBLE PRECISION",
        "date_maj_station": "TIMESTAMP",
        "etat_station": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_projection_station": "TEXT",
        "libelle_region": "TEXT",
        "libelle_station": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "uri_cours_eau": "TEXT",
        "uri_station": "TEXT",
    },

    "hydrobio_indices": {
        "code_banque_reference": "TEXT",
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_indice": "TEXT",
        "code_masse_eau": "TEXT",
        "code_methode": "TEXT",
        "code_operation_prelevement": "TEXT",
        "code_prelevement": "TEXT",
        "code_projection": "TEXT",
        "code_qualification": "TEXT",
        "code_region": "TEXT",
        "code_sous_bassin": "TEXT",
        "code_station_hydrobio": "TEXT",
        "code_support": "TEXT",
        "coordonnee_x": "DOUBLE PRECISION",
        "coordonnee_y": "DOUBLE PRECISION",
        "date_prelevement": "TIMESTAMP",
        "latitude": "DOUBLE PRECISION",
        "libelle_accreditation": "TEXT",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_indice": "TEXT",
        "libelle_masse_eau": "TEXT",
        "libelle_methode": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_region": "TEXT",
        "libelle_sous_bassin": "TEXT",
        "libelle_station_hydrobio": "TEXT",
        "libelle_support": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "resultat_indice": "DOUBLE PRECISION",
        "unite_indice": "TEXT",
        "uri_cours_eau": "TEXT",
        "uri_masse_eau": "TEXT",
        "uri_station_hydrobio": "TEXT",
    },

    "hydrobio_stations": {
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_masse_eau": "TEXT",
        "code_projection": "TEXT",
        "code_region": "TEXT",
        "code_sous_bassin": "TEXT",
        "code_station_hydrobio": "TEXT",
        "codes_appel_taxons": "TEXT",
        "codes_indices": "TEXT",
        "codes_reseaux": "TEXT",
        "codes_supports": "TEXT",
        "coordonnee_x": "DOUBLE PRECISION",
        "coordonnee_y": "DOUBLE PRECISION",
        "latitude": "DOUBLE PRECISION",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_masse_eau": "TEXT",
        "libelle_region": "TEXT",
        "libelle_sous_bassin": "TEXT",
        "libelle_station_hydrobio": "TEXT",
        "libelles_appel_taxons": "TEXT",
        "libelles_indices": "TEXT",
        "libelles_reseaux": "TEXT",
        "libelles_supports": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "uri_cours_eau": "TEXT",
        "uri_masse_eau": "TEXT",
        "uri_station_hydrobio": "TEXT",
    },

    "hydrobio_taxons": {
        "code_appel_taxon": "TEXT",
        "code_banque_reference": "TEXT",
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_lot": "TEXT",
        "code_masse_eau": "TEXT",
        "code_methode": "TEXT",
        "code_operation_prelevement": "TEXT",
        "code_prelevement": "TEXT",
        "code_projection": "TEXT",
        "code_qualification": "TEXT",
        "code_region": "TEXT",
        "code_sous_bassin": "TEXT",
        "code_station_hydrobio": "TEXT",
        "code_support": "TEXT",
        "code_type_resultat": "TEXT",
        "codes_indices_operation": "TEXT",
        "codes_taxons_parents": "TEXT",
        "coordonnee_x": "DOUBLE PRECISION",
        "coordonnee_y": "DOUBLE PRECISION",
        "date_prelevement": "TIMESTAMP",
        "hauteur_moyenne_lame_eau": "DOUBLE PRECISION",
        "largeur_moyenne_lame_eau": "DOUBLE PRECISION",
        "latitude": "DOUBLE PRECISION",
        "libelle_appel_taxon": "TEXT",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_liste_faune_flore": "TEXT",
        "libelle_masse_eau": "TEXT",
        "libelle_methode": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_region": "TEXT",
        "libelle_sous_bassin": "TEXT",
        "libelle_station_hydrobio": "TEXT",
        "libelle_support": "TEXT",
        "libelle_type_resultat": "TEXT",
        "libelles_taxons_parents": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "longueur_prospectee": "DOUBLE PRECISION",
        "resultat_taxon": "DOUBLE PRECISION",
        "uri_cours_eau": "TEXT",
        "uri_masse_eau": "TEXT",
        "uri_station_hydrobio": "TEXT",
    },

    "hydrometry_obs_elab": {
        "code_methode": "TEXT",
        "code_qualification": "TEXT",
        "code_site": "TEXT",
        "code_station": "TEXT",
        "code_statut": "TEXT",
        "date_obs_elab": "TIMESTAMP",
        "date_prod": "TIMESTAMP",
        "grandeur_hydro_elab": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_methode": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_statut": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "resultat_obs_elab": "DOUBLE PRECISION",
    },

    "hydrometry_sites": {
        "altitude_site": "DOUBLE PRECISION",
        "code_commune_site": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_entite_hydro_site": "TEXT",
        "code_projection": "TEXT",
        "code_region": "TEXT",
        "code_site": "TEXT",
        "code_systeme_alti_site": "TEXT",
        "code_troncon_hydro_site": "TEXT",
        "code_zone_hydro_site": "TEXT",
        "commentaire_influence_generale_site": "TEXT",
        "commentaire_site": "TEXT",
        "coordonnee_x_site": "DOUBLE PRECISION",
        "coordonnee_y_site": "DOUBLE PRECISION",
        "date_maj_site": "TIMESTAMP",
        "date_premiere_donnee_dispo_site": "TEXT",
        "grandeur_hydro": "TEXT",
        "influence_generale_site": "BIGINT",
        "latitude_site": "DOUBLE PRECISION",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_region": "TEXT",
        "libelle_site": "TEXT",
        "longitude_site": "DOUBLE PRECISION",
        "premier_mois_annee_hydro_site": "BIGINT",
        "premier_mois_etiage_site": "BIGINT",
        "statut_site": "BIGINT",
        "surface_bv": "DOUBLE PRECISION",
        "type_contexte_loi_stat_site": "TEXT",
        "type_loi_site": "TEXT",
        "type_site": "TEXT",
        "uri_cours_eau": "TEXT",
    },

    "hydrometry_stations": {
        "altitude_ref_alti_station": "DOUBLE PRECISION",
        "code_commune_station": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_finalite_station": "TEXT",
        "code_projection": "TEXT",
        "code_regime_station": "TEXT",
        "code_region": "TEXT",
        "code_sandre_reseau_station": "TEXT",
        "code_site": "TEXT",
        "code_station": "TEXT",
        "code_systeme_alti_site": "TEXT",
        "commentaire_influence_locale_station": "TEXT",
        "commentaire_station": "TEXT",
        "coordlatlon": "TEXT",
        "coordonnee_x_station": "DOUBLE PRECISION",
        "coordonnee_y_station": "DOUBLE PRECISION",
        "date_activation_ref_alti_station": "TIMESTAMP",
        "date_debut_ref_alti_station": "TIMESTAMP",
        "date_fermeture_station": "TIMESTAMP",
        "date_maj_ref_alti_station": "TIMESTAMP",
        "date_maj_station": "TIMESTAMP",
        "date_ouverture_station": "TIMESTAMP",
        "descriptif_station": "TEXT",
        "en_service": "BOOLEAN",
        "influence_locale_station": "TEXT",
        "latitude_station": "DOUBLE PRECISION",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_region": "TEXT",
        "libelle_site": "TEXT",
        "libelle_station": "TEXT",
        "longitude_station": "DOUBLE PRECISION",
        "qualification_donnees_station": "BIGINT",
        "type_contexte_loi_stat_station": "TEXT",
        "type_loi_station": "TEXT",
        "type_station": "TEXT",
        "uri_cours_eau": "TEXT",
    },

    "piezometry_chroniques": {
        "code_bss": "TEXT",
        "urn_bss": "TEXT",
        "date_mesure": "TIMESTAMP",
        "timestamp_mesure": "BIGINT",
        "niveau_nappe_eau": "DOUBLE PRECISION",
        "mode_obtention": "TEXT",
        "statut": "TEXT",
        "qualification": "TEXT",
        "code_continuite": "TEXT",
        "nom_continuite": "TEXT",
        "code_producteur": "TEXT",
        "nom_producteur": "TEXT",
        "code_nature_mesure": "TEXT",
        "nom_nature_mesure": "TEXT",
        "profondeur_nappe": "DOUBLE PRECISION",
    },

    "piezometry_stations": {
        "altitude_station": "DOUBLE PRECISION",
        "bss_id": "TEXT",
        "code_bss": "TEXT",
        "code_commune_insee": "TEXT",
        "code_departement": "TEXT",
        "codes_bdlisa": "TEXT",
        "codes_masse_eau_edl": "TEXT",
        "date_debut_mesure": "TIMESTAMP",
        "date_fin_mesure": "TIMESTAMP",
        "date_maj": "TIMESTAMP",
        "libelle_pe": "TEXT",
        "nb_mesures_piezo": "BIGINT",
        "nom_commune": "TEXT",
        "nom_departement": "TEXT",
        "noms_masse_eau_edl": "TEXT",
        "profondeur_investigation": "DOUBLE PRECISION",
        "urn_bss": "TEXT",
        "urns_bdlisa": "TEXT",
        "urns_masse_eau_edl": "TEXT",
        "x": "DOUBLE PRECISION",
        "y": "DOUBLE PRECISION",
    },

    "prelevements_chroniques": {
        "annee": "BIGINT",
        "code_commune_insee": "TEXT",
        "code_departement": "TEXT",
        "code_mode_obtention_volume": "TEXT",
        "code_ouvrage": "TEXT",
        "code_qualification_volume": "TEXT",
        "code_statut_instruction": "TEXT",
        "code_statut_volume": "TEXT",
        "code_usage": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_departement": "TEXT",
        "libelle_mode_obtention_volume": "TEXT",
        "libelle_qualification_volume": "TEXT",
        "libelle_statut_instruction": "TEXT",
        "libelle_statut_volume": "TEXT",
        "libelle_usage": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "nom_commune": "TEXT",
        "nom_ouvrage": "TEXT",
        "prelevement_ecrasant": "BOOLEAN",
        "producteur_donnee": "TEXT",
        "volume": "DOUBLE PRECISION",
    },

    "prelevements_ouvrages": {
        "code_bdlisa": "TEXT",
        "code_commune_insee": "TEXT",
        "code_departement": "TEXT",
        "code_entite_hydro_cours_eau": "TEXT",
        "code_entite_hydro_plan_eau": "TEXT",
        "code_mer_ocean": "TEXT",
        "code_ouvrage": "TEXT",
        "code_point_referent": "TEXT",
        "code_precision_coord": "TEXT",
        "code_type_milieu": "TEXT",
        "commentaire": "TEXT",
        "date_exploitation_debut": "TIMESTAMP",
        "date_exploitation_fin": "TEXT",
        "id_local_ouvrage": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_departement": "TEXT",
        "libelle_precision_coord": "TEXT",
        "libelle_type_milieu": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "nom_commune": "TEXT",
        "nom_ouvrage": "TEXT",
        "ressource_cont_non_referencee": "BOOLEAN",
        "ressource_cont_non_referencee_info": "TEXT",
        "uri_bdlisa": "TEXT",
        "uri_entite_hydro_cours_eau": "TEXT",
        "uri_entite_hydro_plan_eau": "TEXT",
        "uri_ouvrage": "TEXT",
    },

    "prelevements_points": {
        "code_commune_insee": "TEXT",
        "code_departement": "TEXT",
        "code_entite_hydro_cours_eau": "TEXT",
        "code_entite_hydro_plan_eau": "TEXT",
        "code_mer_ocean": "TEXT",
        "code_nature": "TEXT",
        "code_ouvrage": "TEXT",
        "code_point_prelevement": "TEXT",
        "code_type_milieu": "TEXT",
        "code_zone_hydro": "TEXT",
        "commentaire": "TEXT",
        "date_exploitation_debut": "TIMESTAMP",
        "date_exploitation_fin": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_nature": "TEXT",
        "libelle_type_milieu": "TEXT",
        "lieu_dit": "TEXT",
        "nappe_accompagnement": "BOOLEAN",
        "nom_commune": "TEXT",
        "nom_point_prelevement": "TEXT",
        "uri_bss_point_eau": "TEXT",
        "uri_entite_hydro_cours_eau": "TEXT",
        "uri_entite_hydro_plan_eau": "TEXT",
        "uri_ouvrage": "TEXT",
        "uri_zone_hydro": "TEXT",
    },

    "quality_groundwater_analyses": {
        "altitude": "DOUBLE PRECISION",
        "bss_id": "TEXT",
        "code_bassin_dce": "TEXT",
        "code_bss": "TEXT",
        "code_circonscription_administrative_bassin": "TEXT",
        "code_fraction": "TEXT",
        "code_insee_actuel": "TEXT",
        "code_lieu_analyse": "TEXT",
        "code_methode": "TEXT",
        "code_param": "TEXT",
        "code_producteur": "TEXT",
        "code_qualification": "TEXT",
        "code_region": "TEXT",
        "code_remarque_analyse": "TEXT",
        "code_statut_analyse": "TEXT",
        "code_type_point_eau": "TEXT",
        "code_type_qualito": "TEXT",
        "code_unite": "TEXT",
        "codes_entite_hg_bdlisa": "TEXT",
        "codes_groupe_parametre": "TEXT",
        "codes_masse_eau_edl": "TEXT",
        "codes_masse_eau_rap": "TEXT",
        "codes_reseau": "TEXT",
        "date_debut_prelevement": "TIMESTAMP",
        "incertitude_analytique": "DOUBLE PRECISION",
        "latitude": "DOUBLE PRECISION",
        "limite_detection": "DOUBLE PRECISION",
        "limite_quantification": "DOUBLE PRECISION",
        "longitude": "DOUBLE PRECISION",
        "nom_bassin_dce": "TEXT",
        "nom_circonscription_administrative_bassin": "TEXT",
        "nom_commune_actuel": "TEXT",
        "nom_departement": "TEXT",
        "nom_fraction": "TEXT",
        "nom_lieu_analyse": "TEXT",
        "nom_methode": "TEXT",
        "nom_param": "TEXT",
        "nom_producteur": "TEXT",
        "nom_qualification": "TEXT",
        "nom_region": "TEXT",
        "nom_remarque_analyse": "TEXT",
        "nom_statut_analyse": "TEXT",
        "nom_type_point_eau": "TEXT",
        "nom_type_qualito": "TEXT",
        "nom_unite": "TEXT",
        "noms_entite_hg_bdlisa": "TEXT",
        "noms_groupe_parametre": "TEXT",
        "noms_masse_eau_edl": "TEXT",
        "noms_masse_eau_rap": "TEXT",
        "noms_reseau": "TEXT",
        "num_departement": "TEXT",
        "precision_coordonnees": "DOUBLE PRECISION",
        "resultat": "DOUBLE PRECISION",
        "seuil_saturation": "DOUBLE PRECISION",
        "symbole_unite": "TEXT",
        "uri_fraction": "TEXT",
        "uri_lieu_analyse": "TEXT",
        "uri_methode": "TEXT",
        "uri_param": "TEXT",
        "uri_producteur": "TEXT",
        "uri_qualification": "TEXT",
        "uri_remarque_analyse": "TEXT",
        "uri_statut_analyse": "TEXT",
        "uri_type_qualito": "TEXT",
        "uri_unite": "TEXT",
        "uris_groupe_parametre": "TEXT",
        "uris_reseau": "TEXT",
        "urn_bassin_dce": "TEXT",
        "urn_bss": "TEXT",
        "urns_bdlisa": "TEXT",
        "urns_masse_eau_edl": "TEXT",
        "urns_masse_eau_rap": "TEXT",
    },

    "quality_groundwater_stations": {
        "altitude": "DOUBLE PRECISION",
        "bassin_dce": "TEXT",
        "bss_id": "TEXT",
        "circonscriptions_administrative_bassin": "TEXT",
        "code_bss": "TEXT",
        "code_caracteristique_aquifere": "TEXT",
        "code_etat_pe": "TEXT",
        "code_insee": "TEXT",
        "code_mode_gisement": "TEXT",
        "code_nature_pe": "TEXT",
        "codes_entite_hg_bdlisa": "TEXT",
        "codes_masse_eau_edl": "TEXT",
        "codes_masse_eau_rap": "TEXT",
        "codes_reseau": "TEXT",
        "commentaire_pe": "TEXT",
        "date_debut_mesure": "TIMESTAMP",
        "date_fin_mesure": "TIMESTAMP",
        "latitude": "DOUBLE PRECISION",
        "libelle_pe": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "nom_caracteristique_aquifere": "TEXT",
        "nom_commune": "TEXT",
        "nom_departement": "TEXT",
        "nom_etat_pe": "TEXT",
        "nom_mode_gisement": "TEXT",
        "nom_nature_pe": "TEXT",
        "nom_region": "TEXT",
        "noms_entite_hg_bdlisa": "TEXT",
        "noms_masse_eau_edl": "TEXT",
        "noms_masse_eau_rap": "TEXT",
        "noms_reseau": "TEXT",
        "num_departement": "TEXT",
        "precision_coordonnees": "DOUBLE PRECISION",
        "profondeur_investigation": "DOUBLE PRECISION",
        "uri_caracteristique_aquifere": "TEXT",
        "uri_etat_pe": "TEXT",
        "uri_mode_gisement": "TEXT",
        "uri_nature_pe": "TEXT",
        "uris_reseau": "TEXT",
        "urn_bassin_dce": "TEXT",
        "urn_bss": "TEXT",
        "urns_bdlisa": "TEXT",
        "urns_masse_eau_edl": "TEXT",
        "urns_masse_eau_rap": "TEXT",
    },

    "quality_rivers_analyses": {
        "agrement": "TEXT",
        "code_accreditation": "TEXT",
        "code_analyse": "TEXT",
        "code_banque_reference": "TEXT",
        "code_difficulte_analyse": "TEXT",
        "code_fraction": "TEXT",
        "code_groupe_parametre": "TEXT",
        "code_insitu": "TEXT",
        "code_laboratoire": "TEXT",
        "code_methode_analyse": "TEXT",
        "code_methode_extraction": "TEXT",
        "code_methode_fractionnement": "TEXT",
        "code_operation": "TEXT",
        "code_parametre": "TEXT",
        "code_point_eau_surface": "TEXT",
        "code_prelevement": "TEXT",
        "code_preleveur": "TEXT",
        "code_producteur_analyse": "TEXT",
        "code_qualification": "TEXT",
        "code_remarque": "TEXT",
        "code_reseau": "TEXT",
        "code_station": "TEXT",
        "code_statut": "TEXT",
        "code_support": "TEXT",
        "code_unite": "TEXT",
        "commentaires_analyse": "TEXT",
        "commentaires_resultat_analyse": "TEXT",
        "date_maj_analyse": "TIMESTAMP",
        "date_prelevement": "TIMESTAMP",
        "heure_analyse": "TEXT",
        "heure_prelevement": "TEXT",
        "incertitude_analytique": "DOUBLE PRECISION",
        "latitude": "DOUBLE PRECISION",
        "libelle_fraction": "TEXT",
        "libelle_groupe_parametre": "TEXT",
        "libelle_insitu": "TEXT",
        "libelle_parametre": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_station": "TEXT",
        "libelle_support": "TEXT",
        "limite_detection": "DOUBLE PRECISION",
        "limite_quantification": "DOUBLE PRECISION",
        "limite_saturation": "DOUBLE PRECISION",
        "longitude": "DOUBLE PRECISION",
        "mnemo_accreditation": "TEXT",
        "mnemo_difficulte_analyse": "TEXT",
        "mnemo_remarque": "TEXT",
        "mnemo_statut": "TEXT",
        "nom_laboratoire": "TEXT",
        "nom_methode_analyse": "TEXT",
        "nom_methode_extraction": "TEXT",
        "nom_methode_fractionnement": "TEXT",
        "nom_preleveur": "TEXT",
        "nom_producteur_analyse": "TEXT",
        "nom_reseau": "TEXT",
        "rendement_extraction": "DOUBLE PRECISION",
        "resultat": "DOUBLE PRECISION",
        "symbole_unite": "TEXT",
        "uri_fraction": "TEXT",
        "uri_groupe_parametre": "TEXT",
        "uri_laboratoire": "TEXT",
        "uri_methode_analyse": "TEXT",
        "uri_methode_extraction": "TEXT",
        "uri_methode_fractionnement": "TEXT",
        "uri_parametre": "TEXT",
        "uri_preleveur": "TEXT",
        "uri_producteur_prelevement": "TEXT",
        "uri_reseau": "TEXT",
        "uri_station": "TEXT",
        "uri_support": "TEXT",
        "uri_unite": "TEXT",
    },

    "quality_rivers_conditions": {
        "code_banque_reference": "TEXT",
        "code_eu_masse_deau": "TEXT",
        "code_groupe_parametre": "TEXT",
        "code_masse_deau": "TEXT",
        "code_methode": "TEXT",
        "code_operation_cep": "TEXT",
        "code_parametre": "TEXT",
        "code_point_eau_surface": "TEXT",
        "code_prelevement": "TEXT",
        "code_preleveur": "TEXT",
        "code_producteur": "TEXT",
        "code_qualification": "TEXT",
        "code_remarque": "TEXT",
        "code_station": "TEXT",
        "code_statut": "TEXT",
        "code_unite": "TEXT",
        "commentaire": "TEXT",
        "date_maj": "TIMESTAMP",
        "date_mesure": "TIMESTAMP",
        "date_prelevement": "TIMESTAMP",
        "heure_mesure": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_groupe_parametre": "TEXT",
        "libelle_parametre": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_resultat": "TEXT",
        "libelle_station": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "mnemo_remarque": "TEXT",
        "mnemo_statut": "TEXT",
        "nom_masse_deau": "TEXT",
        "nom_methode": "TEXT",
        "nom_preleveur": "TEXT",
        "nom_producteur": "TEXT",
        "resultat": "TEXT",
        "symbole_unite": "TEXT",
        "uri_groupe_parametre": "TEXT",
        "uri_methode": "TEXT",
        "uri_parametre": "TEXT",
        "uri_preleveur": "TEXT",
        "uri_producteur": "TEXT",
        "uri_station": "TEXT",
        "uri_unite": "TEXT",
    },

    "quality_rivers_operations": {
        "agrement": "TEXT",
        "code_accreditation": "TEXT",
        "code_banque_reference": "TEXT",
        "code_difficulte": "TEXT",
        "code_finalite": "TEXT",
        "code_methode": "TEXT",
        "code_operation": "TEXT",
        "code_point_eau_surface": "TEXT",
        "code_prelevement": "TEXT",
        "code_preleveur": "TEXT",
        "code_producteur": "TEXT",
        "code_projection": "TEXT",
        "code_reseau": "TEXT",
        "code_station": "TEXT",
        "code_support": "TEXT",
        "code_zone_verticale_prospectee": "TEXT",
        "commentaires": "TEXT",
        "date_fin": "TEXT",
        "date_prelevement": "TIMESTAMP",
        "heure_fin": "DOUBLE PRECISION",
        "heure_prelevement": "TIMESTAMP",
        "latitude": "DOUBLE PRECISION",
        "libelle_finalite": "TEXT",
        "libelle_projection": "TEXT",
        "libelle_station": "TEXT",
        "libelle_support": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "mnemo_accreditation": "TEXT",
        "mnemo_difficulte": "TEXT",
        "mnemo_zone_verticale_prospectee": "TEXT",
        "nom_methode": "TEXT",
        "nom_preleveur": "TEXT",
        "nom_producteur": "TEXT",
        "nom_reseau": "TEXT",
        "profondeur": "DOUBLE PRECISION",
        "uri_methode": "TEXT",
        "uri_preleveur": "TEXT",
        "uri_producteur": "TEXT",
        "uri_reseau": "TEXT",
        "uri_station": "TEXT",
        "uri_support": "TEXT",
        "x_prelevement": "DOUBLE PRECISION",
        "y_prelevement": "DOUBLE PRECISION",
    },

    "quality_rivers_stations": {
        "altitude_point_caracteristique": "DOUBLE PRECISION",
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_eu_bassin": "TEXT",
        "code_eu_masse_deau": "TEXT",
        "code_eu_sous_bassin": "TEXT",
        "code_masse_deau": "TEXT",
        "code_projection": "TEXT",
        "code_region": "TEXT",
        "code_station": "TEXT",
        "commentaire": "TEXT",
        "coordonnee_x": "DOUBLE PRECISION",
        "coordonnee_y": "DOUBLE PRECISION",
        "date_arret": "TEXT",
        "date_creation": "TIMESTAMP",
        "date_maj_information": "TIMESTAMP",
        "durete": "DOUBLE PRECISION",
        "finalite": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_commune": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_projection": "TEXT",
        "libelle_region": "TEXT",
        "libelle_station": "TEXT",
        "localisation_precise": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "nature": "TEXT",
        "nom_bassin": "TEXT",
        "nom_cours_eau": "TEXT",
        "nom_masse_deau": "TEXT",
        "nom_sous_bassin": "TEXT",
        "point_kilometrique": "DOUBLE PRECISION",
        "premier_mois_annee_etiage": "DOUBLE PRECISION",
        "superficie_bassin_versant_reel": "DOUBLE PRECISION",
        "superficie_bassin_versant_topo": "DOUBLE PRECISION",
        "type_entite_hydro": "BIGINT",
        "uri_bassin": "TEXT",
        "uri_cours_eau": "TEXT",
        "uri_masse_deau": "TEXT",
        "uri_sous_bassin": "TEXT",
        "uri_station": "TEXT",
    },

    "temperature_chroniques": {
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_parametre": "TEXT",
        "code_qualification": "TEXT",
        "code_station": "TEXT",
        "code_unite": "TEXT",
        "date_mesure_temp": "TIMESTAMP",
        "heure_mesure_temp": "TEXT",
        "latitude": "DOUBLE PRECISION",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_parametre": "TEXT",
        "libelle_qualification": "TEXT",
        "libelle_station": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "resultat": "DOUBLE PRECISION",
        "symbole_unite": "TEXT",
        "uri_cours_eau": "TEXT",
        "uri_station": "TEXT",
    },

    "temperature_stations": {
        "altitude": "DOUBLE PRECISION",
        "code_bassin": "TEXT",
        "code_commune": "TEXT",
        "code_cours_eau": "TEXT",
        "code_departement": "TEXT",
        "code_masse_eau": "TEXT",
        "code_region": "TEXT",
        "code_sous_bassin": "TEXT",
        "code_station": "TEXT",
        "code_troncon_hydro": "TEXT",
        "code_type_projection": "TEXT",
        "coordonnee_x": "DOUBLE PRECISION",
        "coordonnee_y": "DOUBLE PRECISION",
        "date_maj_infos": "TIMESTAMP",
        "latitude": "DOUBLE PRECISION",
        "libelle_bassin": "TEXT",
        "libelle_commune": "TEXT",
        "libelle_cours_eau": "TEXT",
        "libelle_departement": "TEXT",
        "libelle_masse_eau": "TEXT",
        "libelle_region": "TEXT",
        "libelle_sous_bassin": "TEXT",
        "libelle_station": "TEXT",
        "localisation": "TEXT",
        "longitude": "DOUBLE PRECISION",
        "pk": "DOUBLE PRECISION",
        "uri_bassin": "TEXT",
        "uri_cours_eau": "TEXT",
        "uri_masse_eau": "TEXT",
        "uri_station": "TEXT",
    },

}


# ============================================================================
# PRIMARY KEYS
# ============================================================================

TABLE_PK_MAPPING: Dict[str, List[str]] = {
    "hydrometry_stations": ["code_station"],
    "hydrometry_sites": ["code_site"],
    "piezometry_stations": ["code_bss"],
    "piezometry_chroniques": ["code_bss", "date_mesure"],
    "quality_groundwater_stations": ["code_bss"],
    "quality_groundwater_analyses": ["code_bss", "date_debut_prelevement", "code_param"],
    "quality_rivers_stations": ["code_station"],
    "quality_rivers_analyses": ["code_station", "date_prelevement", "code_parametre", "code_fraction"],
    "quality_rivers_operations": ["code_operation"],
    "quality_rivers_conditions": ["code_operation_cep"],
    "temperature_stations": ["code_station"],
    "temperature_chroniques": ["code_station", "date_mesure_temp"],
    "hydrobio_stations": ["code_station_hydrobio"],
    "hydrobio_indices": ["code_station_hydrobio", "date_prelevement", "code_indice"],
    "hydrobio_taxons": ["code_station_hydrobio", "date_prelevement", "code_support", "code_appel_taxon"],
    "ecoulement_stations": ["code_station"],
    "ecoulement_observations": ["code_station", "date_observation"],
    "ecoulement_campagnes": ["code_campagne"],
    "prelevements_ouvrages": ["code_ouvrage"],
    "prelevements_points": ["code_point_prelevement"],
    "prelevements_chroniques": ["code_ouvrage", "annee"],
    "hydrometry_obs_elab": ["code_site", "date_obs_elab"],
}


# ============================================================================
# FOREIGN KEYS
# ============================================================================

TABLE_FK_MAPPING: Dict[str, List[Tuple[str, str, str]]] = {
    # Format: (colonne_locale, table_référencée, colonne_référencée)
    "hydrometry_stations": [("code_site", "hydrometry_sites", "code_site")],
    "piezometry_chroniques": [("code_bss", "piezometry_stations", "code_bss")],
    "quality_groundwater_analyses": [("code_bss", "quality_groundwater_stations", "code_bss")],
    "quality_rivers_analyses": [("code_station", "quality_rivers_stations", "code_station")],
    "temperature_chroniques": [("code_station", "temperature_stations", "code_station")],
    "prelevements_points": [("code_ouvrage", "prelevements_ouvrages", "code_ouvrage")],
}


# ============================================================================
# COLONNES GÉOMÉTRIQUES (longitude, latitude)
# ============================================================================

GEOMETRY_COLUMNS: Dict[str, Tuple[str, str]] = {
    # Format: table_name: (colonne_longitude, colonne_latitude)
    "hydrometry_stations": ("longitude", "latitude"),
    "hydrometry_sites": ("longitude", "latitude"),
    "piezometry_stations": ("x", "y"),  # Coordonnées projetées
    "quality_groundwater_stations": ("longitude", "latitude"),
    "quality_rivers_stations": ("longitude", "latitude"),
    "temperature_stations": ("longitude", "latitude"),
    "ecoulement_stations": ("longitude", "latitude"),
    "hydrobio_stations": ("coordonnee_x", "coordonnee_y"),  # Coordonnées projetées
}


# ============================================================================
# FONCTIONS HELPER
# ============================================================================

def get_table_schema(table_name: str) -> Optional[Dict[str, str]]:
    """Retourne le schéma complet d'une table"""
    return HUBEAU_FIELD_TYPES.get(table_name)


def get_field_type(table_name: str, field_name: str) -> Optional[str]:
    """Retourne le type PostgreSQL d'un champ"""
    schema = HUBEAU_FIELD_TYPES.get(table_name, {})
    return schema.get(field_name)


def get_primary_key(table_name: str) -> List[str]:
    """Retourne la liste des colonnes de clé primaire"""
    return TABLE_PK_MAPPING.get(table_name, [])


def get_foreign_keys(table_name: str) -> List[Tuple[str, str, str]]:
    """Retourne la liste des foreign keys"""
    return TABLE_FK_MAPPING.get(table_name, [])


def has_geometry(table_name: str) -> bool:
    """Vérifie si la table a des colonnes géométriques"""
    return table_name in GEOMETRY_COLUMNS


def get_geometry_columns(table_name: str) -> Tuple[Optional[str], Optional[str]]:
    """Retourne (colonne_longitude, colonne_latitude)"""
    return GEOMETRY_COLUMNS.get(table_name, (None, None))


def get_all_tables() -> List[str]:
    """Retourne la liste de toutes les tables"""
    return list(HUBEAU_FIELD_TYPES.keys())


def get_table_indexes(table_name: str) -> Dict[str, List[str]]:
    """
    Retourne les indexes personnalisés d'une table.

    Note: PostgreSQL crée automatiquement des indexes sur:
    - Les PRIMARY KEY (via TABLE_PK_MAPPING)
    - Les FOREIGN KEY (via TABLE_FK_MAPPING, si activées)

    Cette fonction retourne un dictionnaire vide car les APIs Hub'Eau
    ne spécifient pas d'indexes custom dans leur documentation Swagger.

    Format de retour (si des indexes étaient définis):
    {
        "idx_name": ["column1", "column2"],
        ...
    }

    Returns:
        Dict vide (pas d'indexes custom pour Hub'Eau)
    """
    return {}

