-- ============================================================================
-- Hub'Eau PostgreSQL Schema
-- Auto-généré depuis les fichiers YAML de configuration
-- ============================================================================

-- Créer le schéma
CREATE SCHEMA IF NOT EXISTS hubeau;

-- Activer PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- Table: ecoulement_campagnes
CREATE TABLE IF NOT EXISTS hubeau.ecoulement_campagnes (
    id SERIAL PRIMARY KEY,
    code_campagne INTEGER,
    date_campagne DATE NOT NULL,
    code_type_campagne INTEGER,
    libelle_type_campagne TEXT,
    nombre_modalite_ecoulement INTEGER,
    code_reseau TEXT,
    libelle_reseau TEXT,
    uri_reseau TEXT,
    code_departement TEXT NOT NULL,
    libelle_departement TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour ecoulement_campagnes
CREATE UNIQUE INDEX IF NOT EXISTS ecoulement_campagnes_unique_idx ON hubeau.ecoulement_campagnes(code_departement, date_campagne);

-- Table: ecoulement_observations
CREATE TABLE IF NOT EXISTS hubeau.ecoulement_observations (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    coordonnee_x_station DOUBLE PRECISION,
    coordonnee_y_station DOUBLE PRECISION,
    code_projection_station TEXT,
    libelle_projection_station TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_departement TEXT,
    libelle_departement TEXT,
    code_commune TEXT,
    libelle_commune TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_bassin TEXT,
    libelle_bassin TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    date_observation DATE NOT NULL,
    code_campagne TEXT,
    code_ecoulement TEXT,
    libelle_ecoulement TEXT,
    code_reseau TEXT,
    libelle_reseau TEXT,
    uri_reseau TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour ecoulement_observations
CREATE UNIQUE INDEX IF NOT EXISTS ecoulement_observations_unique_idx ON hubeau.ecoulement_observations(code_station, date_observation);

-- Table: ecoulement_stations
CREATE TABLE IF NOT EXISTS hubeau.ecoulement_stations (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    coordonnee_x_station DOUBLE PRECISION,
    coordonnee_y_station DOUBLE PRECISION,
    code_projection_station TEXT,
    libelle_projection_station TEXT,
    code_epsg_station TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_departement TEXT,
    libelle_departement TEXT,
    code_commune TEXT,
    libelle_commune TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_bassin TEXT,
    libelle_bassin TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    etat_station TEXT,
    date_maj_station TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour ecoulement_stations
CREATE UNIQUE INDEX IF NOT EXISTS ecoulement_stations_unique_idx ON hubeau.ecoulement_stations(code_station);

-- Table: hydrobio_indices
CREATE TABLE IF NOT EXISTS hubeau.hydrobio_indices (
    id SERIAL PRIMARY KEY,
    code_indice TEXT NOT NULL,
    libelle_indice TEXT,
    resultat_indice DOUBLE PRECISION,
    unite_indice TEXT,
    code_station_hydrobio TEXT NOT NULL,
    libelle_station_hydrobio TEXT,
    uri_station_hydrobio TEXT,
    coordonnee_x DOUBLE PRECISION,
    coordonnee_y DOUBLE PRECISION,
    code_projection TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_masse_eau TEXT,
    libelle_masse_eau TEXT,
    uri_masse_eau TEXT,
    code_sous_bassin TEXT,
    libelle_sous_bassin TEXT,
    code_bassin TEXT,
    libelle_bassin TEXT,
    date_prelevement DATE NOT NULL,
    code_prelevement TEXT,
    code_operation_prelevement TEXT,
    code_banque_reference TEXT,
    code_support TEXT NOT NULL,
    libelle_support TEXT,
    code_qualification TEXT,
    libelle_qualification TEXT,
    code_methode TEXT,
    libelle_methode TEXT,
    libelle_accreditation TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrobio_indices
CREATE UNIQUE INDEX IF NOT EXISTS hydrobio_indices_unique_idx ON hubeau.hydrobio_indices(code_station_hydrobio, date_prelevement, code_indice, code_support);

-- Table: hydrobio_stations
CREATE TABLE IF NOT EXISTS hubeau.hydrobio_stations (
    id SERIAL PRIMARY KEY,
    code_station_hydrobio TEXT NOT NULL,
    libelle_station_hydrobio TEXT,
    uri_station_hydrobio TEXT,
    coordonnee_x DOUBLE PRECISION,
    coordonnee_y DOUBLE PRECISION,
    code_projection TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_masse_eau TEXT,
    libelle_masse_eau TEXT,
    uri_masse_eau TEXT,
    code_sous_bassin TEXT,
    libelle_sous_bassin TEXT,
    code_bassin TEXT,
    libelle_bassin TEXT,
    codes_reseaux JSONB,
    libelles_reseaux JSONB,
    codes_supports JSONB,
    libelles_supports JSONB,
    codes_appel_taxons JSONB,
    libelles_appel_taxons JSONB,
    codes_indices JSONB,
    libelles_indices JSONB,
    date_premier_prelevement DATE,
    date_dernier_prelevement DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrobio_stations
CREATE UNIQUE INDEX IF NOT EXISTS hydrobio_stations_unique_idx ON hubeau.hydrobio_stations(code_station_hydrobio);

-- Table: hydrobio_taxons
CREATE TABLE IF NOT EXISTS hubeau.hydrobio_taxons (
    id SERIAL PRIMARY KEY,
    code_appel_taxon TEXT NOT NULL,
    libelle_appel_taxon TEXT,
    codes_taxons_parents JSONB,
    libelles_taxons_parents JSONB,
    code_type_resultat TEXT,
    libelle_type_resultat TEXT,
    resultat_taxon DOUBLE PRECISION,
    code_station_hydrobio TEXT NOT NULL,
    libelle_station_hydrobio TEXT,
    uri_station_hydrobio TEXT,
    coordonnee_x DOUBLE PRECISION,
    coordonnee_y DOUBLE PRECISION,
    code_projection TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_masse_eau TEXT,
    libelle_masse_eau TEXT,
    uri_masse_eau TEXT,
    code_sous_bassin TEXT,
    libelle_sous_bassin TEXT,
    code_bassin TEXT,
    libelle_bassin TEXT,
    date_prelevement DATE NOT NULL,
    code_prelevement TEXT,
    code_operation_prelevement TEXT,
    code_banque_reference TEXT,
    code_support TEXT NOT NULL,
    libelle_support TEXT,
    code_qualification TEXT,
    libelle_qualification TEXT,
    code_methode TEXT,
    libelle_methode TEXT,
    libelle_liste_faune_flore TEXT,
    code_lot TEXT,
    hauteur_moyenne_lame_eau DOUBLE PRECISION,
    largeur_moyenne_lame_eau DOUBLE PRECISION,
    longueur_prospectee DOUBLE PRECISION,
    codes_indices_operation JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrobio_taxons
CREATE UNIQUE INDEX IF NOT EXISTS hydrobio_taxons_unique_idx ON hubeau.hydrobio_taxons(code_station_hydrobio, date_prelevement, code_appel_taxon, code_support);

-- Table: hydrometry_observations
CREATE TABLE IF NOT EXISTS hubeau.hydrometry_observations (
    id SERIAL PRIMARY KEY,
    code_site TEXT,
    code_station TEXT NOT NULL,
    date_obs_elab TIMESTAMP NOT NULL,
    grandeur_hydro_elab TEXT NOT NULL,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    resultat_obs_elab DOUBLE PRECISION,
    date_prod TIMESTAMP,
    code_statut INTEGER,
    libelle_statut TEXT,
    code_qualification INTEGER,
    libelle_qualification TEXT,
    code_methode INTEGER,
    libelle_methode TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrometry_observations
CREATE UNIQUE INDEX IF NOT EXISTS hydrometry_observations_unique_idx ON hubeau.hydrometry_observations(code_station, date_obs_elab, grandeur_hydro_elab);

-- Table: hydrometry_sites
CREATE TABLE IF NOT EXISTS hubeau.hydrometry_sites (
    id SERIAL PRIMARY KEY,
    code_site TEXT NOT NULL,
    libelle_site TEXT,
    type_site TEXT,
    coordonnee_x_site DOUBLE PRECISION,
    coordonnee_y_site DOUBLE PRECISION,
    code_projection INTEGER,
    longitude_site DOUBLE PRECISION,
    latitude_site DOUBLE PRECISION,
    altitude_site DOUBLE PRECISION,
    code_systeme_alti_site INTEGER,
    code_commune_site JSONB,
    libelle_commune JSONB,
    code_departement JSONB,
    libelle_departement JSONB,
    code_region JSONB,
    libelle_region JSONB,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_entite_hydro_site TEXT,
    code_troncon_hydro_site TEXT,
    code_zone_hydro_site TEXT,
    surface_bv DOUBLE PRECISION,
    premier_mois_etiage_site INTEGER,
    premier_mois_annee_hydro_site INTEGER,
    statut_site INTEGER,
    influence_generale_site INTEGER,
    commentaire_influence_generale_site TEXT,
    commentaire_site TEXT,
    grandeur_hydro TEXT,
    date_premiere_donnee_dispo_site DATE,
    date_maj_site TIMESTAMP,
    type_contexte_loi_stat_site TEXT,
    type_loi_site TEXT,
    geometry JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrometry_sites
CREATE UNIQUE INDEX IF NOT EXISTS hydrometry_sites_unique_idx ON hubeau.hydrometry_sites(code_site);

-- Table: hydrometry_stations
CREATE TABLE IF NOT EXISTS hubeau.hydrometry_stations (
    id SERIAL PRIMARY KEY,
    code_site TEXT,
    libelle_site TEXT,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    coordonnee_x_station DOUBLE PRECISION,
    coordonnee_y_station DOUBLE PRECISION,
    code_projection INTEGER,
    longitude_station DOUBLE PRECISION,
    latitude_station DOUBLE PRECISION,
    altitude_ref_alti_station DOUBLE PRECISION,
    code_systeme_alti_site INTEGER,
    code_commune_station TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    type_station TEXT,
    influence_locale_station INTEGER,
    commentaire_influence_locale_station TEXT,
    commentaire_station TEXT,
    descriptif_station TEXT,
    en_service BOOLEAN,
    date_ouverture_station DATE,
    date_fermeture_station DATE,
    date_maj_station TIMESTAMP,
    code_regime_station INTEGER,
    qualification_donnees_station INTEGER,
    code_finalite_station TEXT,
    type_contexte_loi_stat_station TEXT,
    type_loi_station TEXT,
    code_sandre_reseau_station JSONB,
    date_debut_ref_alti_station DATE,
    date_activation_ref_alti_station DATE,
    date_maj_ref_alti_station DATE,
    geometry JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour hydrometry_stations
CREATE UNIQUE INDEX IF NOT EXISTS hydrometry_stations_unique_idx ON hubeau.hydrometry_stations(code_station);

-- Table: piezometry_chroniques
CREATE TABLE IF NOT EXISTS hubeau.piezometry_chroniques (
    id SERIAL PRIMARY KEY,
    code_bss TEXT NOT NULL,
    bss_id TEXT,
    urn_bss TEXT,
    date_mesure DATE,
    timestamp_mesure TIMESTAMP NOT NULL,
    date_maj TIMESTAMP,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    altitude_station DOUBLE PRECISION,
    altitude_repere DOUBLE PRECISION,
    niveau_eau_ngf DOUBLE PRECISION,
    profondeur_nappe DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour piezometry_chroniques
CREATE UNIQUE INDEX IF NOT EXISTS piezometry_chroniques_unique_idx ON hubeau.piezometry_chroniques(code_bss, timestamp_mesure);

-- Table: piezometry_stations
CREATE TABLE IF NOT EXISTS hubeau.piezometry_stations (
    id SERIAL PRIMARY KEY,
    code_bss TEXT NOT NULL,
    bss_id TEXT,
    urn_bss TEXT,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    geometry JSONB,
    code_commune_insee TEXT,
    nom_commune TEXT,
    code_departement TEXT,
    nom_departement TEXT,
    altitude_station DOUBLE PRECISION,
    profondeur_investigation DOUBLE PRECISION,
    libelle_pe TEXT,
    date_debut_mesure DATE,
    date_fin_mesure DATE,
    nb_mesures_piezo INTEGER,
    date_maj TIMESTAMP,
    codes_bdlisa JSONB,
    urns_bdlisa JSONB,
    codes_masse_eau_edl JSONB,
    noms_masse_eau_edl JSONB,
    urns_masse_eau_edl JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour piezometry_stations
CREATE UNIQUE INDEX IF NOT EXISTS piezometry_stations_unique_idx ON hubeau.piezometry_stations(code_bss);

-- Table: prelevements_chroniques
CREATE TABLE IF NOT EXISTS hubeau.prelevements_chroniques (
    id SERIAL PRIMARY KEY,
    code_ouvrage TEXT NOT NULL,
    nom_ouvrage TEXT,
    uri_ouvrage TEXT,
    annee INTEGER NOT NULL,
    code_usage TEXT NOT NULL,
    libelle_usage TEXT,
    volume DOUBLE PRECISION,
    code_statut_volume TEXT,
    libelle_statut_volume TEXT,
    code_qualification_volume TEXT,
    libelle_qualification_volume TEXT,
    code_statut_instruction TEXT,
    libelle_statut_instruction TEXT,
    code_mode_obtention_volume TEXT,
    libelle_mode_obtention_volume TEXT,
    prelevement_ecrasant BOOLEAN,
    producteur_donnee TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune_insee TEXT,
    nom_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour prelevements_chroniques
CREATE UNIQUE INDEX IF NOT EXISTS prelevements_chroniques_unique_idx ON hubeau.prelevements_chroniques(code_ouvrage, annee, code_usage);

-- Table: prelevements_ouvrages
CREATE TABLE IF NOT EXISTS hubeau.prelevements_ouvrages (
    id SERIAL PRIMARY KEY,
    code_ouvrage TEXT NOT NULL,
    nom_ouvrage TEXT,
    uri_ouvrage TEXT,
    id_local_ouvrage TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    code_precision_coord TEXT,
    libelle_precision_coord TEXT,
    geometry JSONB,
    code_commune_insee TEXT,
    nom_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_type_milieu TEXT,
    libelle_type_milieu TEXT,
    code_entite_hydro_cours_eau TEXT,
    uri_entite_hydro_cours_eau TEXT,
    code_entite_hydro_plan_eau TEXT,
    uri_entite_hydro_plan_eau TEXT,
    code_mer_ocean TEXT,
    ressource_cont_non_referencee BOOLEAN,
    ressource_cont_non_referencee_info TEXT,
    code_point_referent TEXT,
    code_bdlisa TEXT,
    uri_bdlisa TEXT,
    codes_points_prelevements JSONB,
    date_exploitation_debut DATE,
    date_exploitation_fin DATE,
    commentaire TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour prelevements_ouvrages
CREATE UNIQUE INDEX IF NOT EXISTS prelevements_ouvrages_unique_idx ON hubeau.prelevements_ouvrages(code_ouvrage);

-- Table: prelevements_points
CREATE TABLE IF NOT EXISTS hubeau.prelevements_points (
    id SERIAL PRIMARY KEY,
    code_point_prelevement TEXT NOT NULL,
    nom_point_prelevement TEXT,
    code_ouvrage TEXT,
    uri_ouvrage TEXT,
    code_type_milieu TEXT,
    libelle_type_milieu TEXT,
    code_nature TEXT,
    libelle_nature TEXT,
    lieu_dit TEXT,
    code_commune_insee TEXT,
    nom_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_entite_hydro_cours_eau TEXT,
    uri_entite_hydro_cours_eau TEXT,
    code_entite_hydro_plan_eau TEXT,
    uri_entite_hydro_plan_eau TEXT,
    code_zone_hydro TEXT,
    uri_zone_hydro TEXT,
    code_mer_ocean TEXT,
    nappe_accompagnement BOOLEAN,
    uri_bss_point_eau TEXT,
    code_bss_point_eau TEXT,
    code_bdlisa TEXT,
    uri_bdlisa JSONB,
    date_exploitation_debut DATE,
    date_exploitation_fin DATE,
    commentaire TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour prelevements_points
CREATE UNIQUE INDEX IF NOT EXISTS prelevements_points_unique_idx ON hubeau.prelevements_points(code_point_prelevement);

-- Table: quality_groundwater_analyses
CREATE TABLE IF NOT EXISTS hubeau.quality_groundwater_analyses (
    id SERIAL PRIMARY KEY,
    code_bss TEXT NOT NULL,
    bss_id TEXT,
    urn_bss TEXT,
    precision_coordonnees TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    altitude TEXT,
    code_insee_actuel TEXT,
    nom_commune_actuel TEXT,
    num_departement TEXT,
    nom_departement TEXT,
    code_region TEXT,
    nom_region TEXT,
    code_circonscription_administrative_bassin TEXT,
    nom_circonscription_administrative_bassin TEXT,
    code_bassin_dce TEXT,
    nom_bassin_dce TEXT,
    urn_bassin_dce TEXT,
    code_type_point_eau INTEGER,
    nom_type_point_eau TEXT,
    codes_entite_hg_bdlisa TEXT,
    noms_entite_hg_bdlisa TEXT,
    urns_bdlisa JSONB,
    codes_masse_eau_rap TEXT,
    noms_masse_eau_rap TEXT,
    urns_masse_eau_rap JSONB,
    codes_masse_eau_edl TEXT,
    noms_masse_eau_edl TEXT,
    urns_masse_eau_edl JSONB,
    codes_reseau TEXT,
    noms_reseau TEXT,
    uris_reseau JSONB,
    code_type_qualito INTEGER,
    nom_type_qualito TEXT,
    uri_type_qualito TEXT,
    date_debut_prelevement DATE NOT NULL,
    code_param INTEGER NOT NULL,
    nom_param TEXT,
    uri_param TEXT,
    code_fraction INTEGER NOT NULL,
    nom_fraction TEXT,
    uri_fraction TEXT,
    resultat DOUBLE PRECISION,
    code_remarque_analyse INTEGER,
    nom_remarque_analyse TEXT,
    uri_remarque_analyse TEXT,
    code_unite TEXT,
    nom_unite TEXT,
    symbole_unite TEXT,
    uri_unite TEXT,
    code_statut_analyse TEXT,
    nom_statut_analyse TEXT,
    uri_statut_analyse TEXT,
    code_qualification TEXT,
    nom_qualification TEXT,
    uri_qualification TEXT,
    limite_quantification DOUBLE PRECISION,
    limite_detection DOUBLE PRECISION,
    seuil_saturation DOUBLE PRECISION,
    incertitude_analytique DOUBLE PRECISION,
    codes_groupe_parametre JSONB,
    noms_groupe_parametre JSONB,
    uris_groupe_parametre JSONB,
    code_producteur TEXT,
    nom_producteur TEXT,
    uri_producteur TEXT,
    code_lieu_analyse INTEGER,
    nom_lieu_analyse TEXT,
    uri_lieu_analyse TEXT,
    code_methode INTEGER,
    nom_methode TEXT,
    uri_methode TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_groundwater_analyses
CREATE UNIQUE INDEX IF NOT EXISTS quality_groundwater_analyses_unique_idx ON hubeau.quality_groundwater_analyses(code_bss, date_debut_prelevement, code_param, code_fraction);

-- Table: quality_groundwater_stations
CREATE TABLE IF NOT EXISTS hubeau.quality_groundwater_stations (
    id SERIAL PRIMARY KEY,
    code_bss TEXT NOT NULL,
    bss_id TEXT,
    urn_bss TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    precision_coordonnees TEXT,
    geometry JSONB,
    code_insee TEXT,
    nom_commune TEXT,
    num_departement TEXT,
    nom_departement TEXT,
    nom_region TEXT,
    circonscriptions_administrative_bassin JSONB,
    bassin_dce TEXT,
    code_bassin_dce TEXT,
    urn_bassin_dce TEXT,
    code_nature_pe INTEGER,
    nom_nature_pe TEXT,
    uri_nature_pe TEXT,
    libelle_pe TEXT,
    code_etat_pe TEXT,
    nom_etat_pe TEXT,
    uri_etat_pe TEXT,
    commentaire_pe TEXT,
    code_caracteristique_aquifere TEXT,
    nom_caracteristique_aquifere TEXT,
    uri_caracteristique_aquifere TEXT,
    code_mode_gisement INTEGER,
    nom_mode_gisement TEXT,
    uri_mode_gisement TEXT,
    profondeur_investigation DOUBLE PRECISION,
    codes_entite_hg_bdlisa TEXT,
    noms_entite_hg_bdlisa TEXT,
    urns_bdlisa JSONB,
    codes_masse_eau_rap TEXT,
    noms_masse_eau_rap TEXT,
    urns_masse_eau_rap JSONB,
    codes_masse_eau_edl TEXT,
    noms_masse_eau_edl TEXT,
    urns_masse_eau_edl JSONB,
    codes_reseau JSONB,
    noms_reseau JSONB,
    uris_reseau JSONB,
    date_debut_mesure DATE,
    date_fin_mesure DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_groundwater_stations
CREATE UNIQUE INDEX IF NOT EXISTS quality_groundwater_stations_unique_idx ON hubeau.quality_groundwater_stations(code_bss);

-- Table: quality_rivers_analyses
CREATE TABLE IF NOT EXISTS hubeau.quality_rivers_analyses (
    id SERIAL PRIMARY KEY,
    code_analyse TEXT,
    code_prelevement TEXT,
    code_operation TEXT,
    code_point_eau_surface TEXT,
    code_banque_reference TEXT,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    date_prelevement DATE NOT NULL,
    heure_prelevement TIME,
    date_maj_analyse TIMESTAMP,
    heure_analyse TIME,
    code_support TEXT NOT NULL,
    libelle_support TEXT,
    uri_support TEXT,
    code_fraction TEXT NOT NULL,
    libelle_fraction TEXT,
    uri_fraction TEXT,
    code_parametre TEXT NOT NULL,
    libelle_parametre TEXT,
    uri_parametre TEXT,
    code_groupe_parametre JSONB,
    libelle_groupe_parametre JSONB,
    uri_groupe_parametre JSONB,
    resultat DOUBLE PRECISION,
    code_unite TEXT,
    symbole_unite TEXT,
    uri_unite TEXT,
    limite_detection DOUBLE PRECISION,
    limite_quantification DOUBLE PRECISION,
    limite_saturation DOUBLE PRECISION,
    incertitude_analytique DOUBLE PRECISION,
    code_qualification TEXT,
    libelle_qualification TEXT,
    code_statut TEXT,
    mnemo_statut TEXT,
    code_remarque TEXT,
    mnemo_remarque TEXT,
    code_insitu TEXT,
    libelle_insitu TEXT,
    code_difficulte_analyse TEXT,
    mnemo_difficulte_analyse TEXT,
    code_methode_analyse TEXT,
    nom_methode_analyse TEXT,
    uri_methode_analyse TEXT,
    code_methode_fractionnement TEXT,
    nom_methode_fractionnement TEXT,
    uri_methode_fractionnement TEXT,
    code_methode_extraction TEXT,
    nom_methode_extraction TEXT,
    uri_methode_extraction TEXT,
    rendement_extraction DOUBLE PRECISION,
    code_accreditation TEXT,
    mnemo_accreditation TEXT,
    agrement TEXT,
    commentaires_analyse TEXT,
    commentaires_resultat_analyse TEXT,
    code_reseau JSONB,
    nom_reseau JSONB,
    uri_reseau JSONB,
    code_producteur_analyse TEXT,
    nom_producteur_analyse TEXT,
    uri_producteur_prelevement TEXT,
    code_preleveur TEXT,
    nom_preleveur TEXT,
    uri_preleveur TEXT,
    code_laboratoire TEXT,
    nom_laboratoire TEXT,
    uri_laboratoire TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_rivers_analyses
CREATE UNIQUE INDEX IF NOT EXISTS quality_rivers_analyses_unique_idx ON hubeau.quality_rivers_analyses(code_station, date_prelevement, code_parametre, code_support, code_fraction);

-- Table: quality_rivers_conditions
CREATE TABLE IF NOT EXISTS hubeau.quality_rivers_conditions (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    code_prelevement TEXT,
    code_operation_cep TEXT,
    code_banque_reference TEXT,
    code_point_eau_surface TEXT,
    code_parametre TEXT NOT NULL,
    libelle_parametre TEXT,
    uri_parametre TEXT,
    code_groupe_parametre JSONB,
    libelle_groupe_parametre JSONB,
    uri_groupe_parametre JSONB,
    resultat DOUBLE PRECISION,
    libelle_resultat TEXT,
    code_unite TEXT,
    symbole_unite TEXT,
    uri_unite TEXT,
    date_prelevement DATE NOT NULL,
    date_mesure DATE,
    heure_mesure TIME,
    date_maj TIMESTAMP,
    code_qualification TEXT,
    libelle_qualification TEXT,
    code_statut TEXT,
    mnemo_statut TEXT,
    code_remarque TEXT,
    mnemo_remarque TEXT,
    code_methode TEXT,
    nom_methode TEXT,
    uri_methode TEXT,
    code_producteur TEXT,
    nom_producteur TEXT,
    uri_producteur TEXT,
    code_preleveur TEXT,
    nom_preleveur TEXT,
    uri_preleveur TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_masse_deau TEXT,
    code_eu_masse_deau TEXT,
    nom_masse_deau TEXT,
    commentaire TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_rivers_conditions
CREATE UNIQUE INDEX IF NOT EXISTS quality_rivers_conditions_unique_idx ON hubeau.quality_rivers_conditions(code_station, date_prelevement, code_parametre);

-- Table: quality_rivers_operations
CREATE TABLE IF NOT EXISTS hubeau.quality_rivers_operations (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    code_operation TEXT NOT NULL,
    code_prelevement TEXT,
    code_point_eau_surface TEXT,
    code_banque_reference TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    x_prelevement DOUBLE PRECISION,
    y_prelevement DOUBLE PRECISION,
    code_projection TEXT,
    libelle_projection TEXT,
    geometry JSONB,
    date_prelevement DATE NOT NULL,
    heure_prelevement TIME,
    date_fin DATE,
    heure_fin TIME,
    code_support TEXT,
    libelle_support TEXT,
    uri_support TEXT,
    code_methode TEXT,
    nom_methode TEXT,
    uri_methode TEXT,
    code_zone_verticale_prospectee TEXT,
    mnemo_zone_verticale_prospectee TEXT,
    profondeur DOUBLE PRECISION,
    code_difficulte TEXT,
    mnemo_difficulte TEXT,
    code_accreditation TEXT,
    mnemo_accreditation TEXT,
    agrement TEXT,
    code_finalite TEXT,
    libelle_finalite TEXT,
    code_reseau TEXT,
    nom_reseau TEXT,
    uri_reseau TEXT,
    code_producteur TEXT,
    nom_producteur TEXT,
    uri_producteur TEXT,
    code_preleveur TEXT,
    nom_preleveur TEXT,
    uri_preleveur TEXT,
    commentaires TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_rivers_operations
CREATE UNIQUE INDEX IF NOT EXISTS quality_rivers_operations_unique_idx ON hubeau.quality_rivers_operations(code_station, date_prelevement, code_operation);

-- Table: quality_rivers_stations
CREATE TABLE IF NOT EXISTS hubeau.quality_rivers_stations (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    coordonnee_x DOUBLE PRECISION,
    coordonnee_y DOUBLE PRECISION,
    code_projection TEXT,
    libelle_projection TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_cours_eau TEXT,
    nom_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_masse_deau TEXT,
    code_eu_masse_deau TEXT,
    nom_masse_deau TEXT,
    uri_masse_deau TEXT,
    code_eu_sous_bassin TEXT,
    nom_sous_bassin TEXT,
    uri_sous_bassin TEXT,
    code_bassin TEXT,
    code_eu_bassin TEXT,
    nom_bassin TEXT,
    uri_bassin TEXT,
    durete TEXT,
    type_entite_hydro TEXT,
    nature TEXT,
    localisation_precise TEXT,
    point_kilometrique DOUBLE PRECISION,
    altitude_point_caracteristique DOUBLE PRECISION,
    superficie_bassin_versant_reel DOUBLE PRECISION,
    superficie_bassin_versant_topo DOUBLE PRECISION,
    premier_mois_annee_etiage BIGINT,
    finalite TEXT,
    commentaire TEXT,
    date_creation DATE,
    date_arret DATE,
    date_maj_information TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour quality_rivers_stations
CREATE UNIQUE INDEX IF NOT EXISTS quality_rivers_stations_unique_idx ON hubeau.quality_rivers_stations(code_station);

-- Table: temperature_chroniques
CREATE TABLE IF NOT EXISTS hubeau.temperature_chroniques (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    localisation TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_parametre TEXT,
    libelle_parametre TEXT,
    date_mesure_temp TIMESTAMP NOT NULL,
    heure_mesure_temp TIME,
    resultat DOUBLE PRECISION,
    code_unite TEXT,
    symbole_unite TEXT,
    code_qualification TEXT,
    libelle_qualification TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour temperature_chroniques
CREATE UNIQUE INDEX IF NOT EXISTS temperature_chroniques_unique_idx ON hubeau.temperature_chroniques(code_station, date_mesure_temp);

-- Table: temperature_stations
CREATE TABLE IF NOT EXISTS hubeau.temperature_stations (
    id SERIAL PRIMARY KEY,
    code_station TEXT NOT NULL,
    libelle_station TEXT,
    uri_station TEXT,
    coordonnee_x DOUBLE PRECISION,
    coordonnee_y DOUBLE PRECISION,
    code_type_projection INTEGER,
    libelle_type_projection TEXT,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    pk DOUBLE PRECISION,
    localisation TEXT,
    geometry JSONB,
    code_commune TEXT,
    libelle_commune TEXT,
    code_departement TEXT,
    libelle_departement TEXT,
    code_region TEXT,
    libelle_region TEXT,
    code_troncon_hydro TEXT,
    code_cours_eau TEXT,
    libelle_cours_eau TEXT,
    uri_cours_eau TEXT,
    code_masse_eau TEXT,
    code_eu_masse_eau TEXT,
    libelle_masse_eau TEXT,
    uri_masse_eau TEXT,
    code_sous_bassin TEXT,
    libelle_sous_bassin TEXT,
    uri_sous_bassin TEXT,
    code_bassin TEXT,
    code_eu_bassin TEXT,
    libelle_bassin TEXT,
    uri_bassin TEXT,
    superficie_topo DOUBLE PRECISION,
    superficie_reelle DOUBLE PRECISION,
    premier_mois_etiage BIGINT,
    nature_station TEXT,
    type_entite_hydro TEXT,
    commentaire TEXT,
    date_mise_en_service DATE,
    date_mise_hors_service DATE,
    date_maj_infos TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index unique pour temperature_stations
CREATE UNIQUE INDEX IF NOT EXISTS temperature_stations_unique_idx ON hubeau.temperature_stations(code_station);

-- ============================================================================
-- Permissions
-- ============================================================================
GRANT ALL PRIVILEGES ON SCHEMA hubeau TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hubeau TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hubeau TO postgres;
