hubeau_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      user: "{{ env_var('PG_USER', 'postgres') }}"
      password: "{{ env_var('PG_PASSWORD', 'REDACTED') }}"
      port: "{{ env_var('PG_PORT', '5432') | int }}"
      dbname: "{{ env_var('PG_DB', 'postgres') }}"
      schema: public # temporary schema
      threads: 1
