resource:
  name: ecoulement_campagnes
  endpoint: /campagnes.csv
  base_url: https://hubeau.eaufrance.fr/api/v1/ecoulement
  primary_key:
  - code_campagne
extraction:
  default_params: {}
performance:
  parallelism: 5
  batch_size: 5000
  retry_times: 3
  retry_delay: 2.0
  rate_limit: 2.0
