resource:
  name: piezometry_chroniques
  endpoint: /chroniques_tr.csv
  base_url: https://hubeau.eaufrance.fr/api/v1/niveaux_nappes
  primary_key:
  - code_bss
  - timestamp_mesure
extraction:
  default_params: {}
performance:
  parallelism: 5
  chunk_size: 10000
  batch_size: 50000
  retry_times: 3
  retry_delay: 2.0
  rate_limit: 2.0
