resource:
  name: quality_groundwater_analyses
  endpoint: /analyses.csv
  base_url: https://hubeau.eaufrance.fr/api/v1/qualite_nappes
  primary_key:
  - code_bss
  - date_debut_prelevement
  - code_param
  - code_fraction
extraction:
  default_params: {}
performance:
  parallelism: 3
  batch_size: 5000
  retry_times: 3
  retry_delay: 2.0
  rate_limit: 2.0
