resource:
  name: quality_rivers_conditions
  endpoint: /condition_environnementale_pc.csv
  base_url: https://hubeau.eaufrance.fr/api/v2/qualite_rivieres
  primary_key:
  - code_station
  - date_prelevement
  - code_parametre
extraction:
  default_params: {}
performance:
  parallelism: 3
  batch_size: 5000
  retry_times: 3
  retry_delay: 2.0
  rate_limit: 2.0
